name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]

body:
  - type: textarea
    attributes:
      label: Description?
      description: Describe this bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How did the bug occur.
      description: Describe in detail how the bug occurred (step by step).
      value: |
        1. ...
        2. ...

    validations:
      required: true

  - type: textarea
    attributes:
      label: The difference from the correct state.
      description: Describe the differences from the correct state.
    validations:
      required: false

  - type: input
    attributes:
      label: Link
      description: Link to reproduce the error.
    validations:
      required: false

  - type: input
    attributes:
      label: Package
      description: The package name and version where the error occurs.
      placeholder: "godown:3.0.0"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment.
      description: The environment that caused the error.
      value: |
        - Browser: Chrome 129
        - JavaScript runtime: Node.js 22.3
        - Package manager: pnpm 9.11.0
        - Other: ...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Error messages.
      description: Console messages or other error warnings.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional messages.
    validations:
      required: false
